id: P007080
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14780
  title: རྒྱལ་ཐང་གི་ལོ་རྒྱུས་ཡིག་ཚགས་དཔྱད་གཞི་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    4eafe892356b4aadadf17ef38fb3fcc9:
      image_group_id: I1KG14835
      title: ''
      volume_number: 1
      total_pages: 308
ebook_metadata:
  title: རྒྱལ་ཐང་གི་ལོ་རྒྱུས་ཡིག་ཚགས་དཔྱད་གཞི་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P007080
  cover: cover.jpg
  layers:
  - pagination
