id: P007080
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14780
  title: རྒྱལ་ཐང་གི་ལོ་རྒྱུས་ཡིག་ཚགས་དཔྱད་གཞི་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    65a72fe5fbfb4a7e8ad1e63b3f36654b:
      image_group_id: I1KG14835
      title: Volume 1 of rgyal thang gi lo rgyus yig tshags dpyad gzhi phyogs bsgrigs/
      volume_number: 1
      total_pages: 308
      base_file: v001.txt
ebook_metadata:
  title: རྒྱལ་ཐང་གི་ལོ་རྒྱུས་ཡིག་ཚགས་དཔྱད་གཞི་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P007080
  cover: cover.jpg
  layers:
  - pagination
